<?php

/** @var string $html_title */
/** @var string $html_body */

?>

<!DOCTYPE html>
<html lang="cs">

<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styles.css">
    <title>
        <?= $html_title ?>
    </title>
</head>

<body>
<div class="findRoute">

    <?= $html_body ?>

</div>
<script src=https://code.jquery.com/jquery-latest.min.js></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<!--<script src="js/ajax.js"></script>-->

</body>

</html>
